[project]
name = "wmc-dab-evaluation"
version = "0.1.0"
description = "How to use Databricks Asset Bundles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks-cli>=0.18.0",
    "ipython>=9.7.0",
]
